crud_pr3/avia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('pilots.urls'))
]

crud_pr3/pilots/urls.py
from django.urls import path
from .views import get_info, get_pilots, detail, add_pilots, update_pilots


app_name = 'pilots'
urlpatterns = [
    path('', get_info, name='get_info'),
    path('pilots/<int:pk>', get_pilots, name='get_pilots'),
    path('pilots/detail/<int:pk>', detail, name='detail'),
    path('add_pilots', add_pilots, name='add_pilots'),
    path('update/<int:pk>', update_pilots, name='update'),
]

crud_pr3/pilots/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150)
    
    class Meta:
        db_table = 'category'
        
    def __str__(self) -> str:
        return self.name


class Pilots(models.Model):
    category = models.ForeignKey(to="Category", on_delete=models.CASCADE)
    model = models.CharField(max_length=100)
    make = models.CharField(max_length=100)
    body = models.TextField()
    price = models.IntegerField()
    image = models.ImageField(upload_to='pilots/', blank=True, null=True)
    
    class Meta:
        db_table = 'pilots'
        
    def __str__(self) -> str:
        return f"{self.category.name}  {self.model}"

crud_pr3/pilots/forms.py
from django.forms import ModelForm
from .models import Pilots


class ProductForm(ModelForm):
    class Meta:
        model = Pilots
        fields = '__all__'

crud_pr3/pilots/views.py
from django.shortcuts import render, redirect
from .forms import PilotForm
from .models import Category, Pilots
# Create your views here.


def get_info(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'index.html', context=context)

def get_pilots(request, pk):
    pilots = pilots.objects.filter(category=pk)
    context = {
        'Pilots': pilots
    }
    return render(request, 'pilots.html', context=context)

def detail(request, pk):
    pilot = Pilots.objects.get(pk=pk)
    context = {
        'pilot': pilot
    }
    return render(request, 'detail.html', context=context)

def add_pilots(request):
    form = PilotForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('pilots:get_info')
    context = {
        'form': form
        }
    return render(request, 'create.html', context=context)


def update_pilots(request, pk):
    data = Pilots.objects.get(pk=pk)
    form = PilotForm(request.POST, request.FILES, instance=data)
    if form.is_valid():
        print(1)
        form.save()
        return redirect('pilots:get_info')
    context = {
        'form': form
        }
    return render(request, 'update.html', context=context)

crud_pr3/templates/create.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
</form>

crud_pr3/templates/detail.html
<title>Detail</title>



<body>
<img src="{{ pilot.image.url }}"/><br>
Model: {{ product.model }}<br>
pilotrice: {{ pilot.productrice }}<br>
Make: {{ pilot.make }}<br>
CAtegory: {{ pilot.category }}<br>
Body: {{ pilot.body }}<hr/>

<a href="{% url 'pilot:get_info'%}" >home</a><br>
<a href="{% url 'pilots:update' pilots.pk %}" >Update</a><br>

</body>

crud_pr3/templates/index.html
<h1>Home Page</h1><br>

<h3>Categories</h3><br>

<body>
{% for category in categories %}
<a href="{% url 'pilots:get_pilots' category.pk %}" >{{ category.name }}</a><br>
{% endfor %}
<a href="{% url 'pilots:add_products' %}" ><b>Add Pilots</b></a><br>


</body>

crud_pr3/templates/pilots.html
<title>Pilots</title>

<h1>Pilots</h1><br>


<body>
{% for pilot in pilots %}
    <a href="{% url 'pilots:detail' pilot.pk %}" >{{ pilot.model }}</a><hr>
{% endfor %}

</body>

crud_pr3/templates/update.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
</form>