crud_pr2/crudproject2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('products.urls'))
]

crud_pr2/products/urls.py
from django.urls import path
from .views import get_info, get_products, detail, add_products, update_products


app_name = 'products'
urlpatterns = [
    path('', get_info, name='get_info'),
    path('products/<int:pk>', get_products, name='get_products'),
    path('products/detail/<int:pk>', detail, name='detail'),
    path('add_products', add_products, name='add_products'),
    path('update/<int:pk>', update_products, name='update'),
]

crud_pr2/products/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=150)
    
    class Meta:
        db_table = 'category'
        
    def __str__(self) -> str:
        return self.name


class Products(models.Model):
    category = models.ForeignKey(to="Category", on_delete=models.CASCADE)
    model = models.CharField(max_length=100)
    make = models.CharField(max_length=100)
    body = models.TextField()
    price = models.IntegerField()
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    
    class Meta:
        db_table = 'products'
        
    def __str__(self) -> str:
        return f"{self.category.name}  {self.model}"
    

crud_pr2/products/forms.py
from django.forms import ModelForm
from .models import Products


class ProductForm(ModelForm):
    class Meta:
        model = Products
        fields = '__all__'

crud_pr2/products/views.py
from django.shortcuts import render, redirect
from .forms import ProductForm
from .models import Category, Products


def get_info(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'index.html', context=context)

def get_products(request, pk):
    products = Products.objects.filter(category=pk)
    context = {
        'products': products
    }
    return render(request, 'products.html', context=context)

def detail(request, pk):
    product = Products.objects.get(pk=pk)
    context = {
        'product': product
    }
    return render(request, 'detail.html', context=context)

def add_products(request):
    form = ProductForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('products:get_info')
    context = {
        'form': form
        }
    return render(request, 'create.html', context=context)


def update_products(request, pk):
    data = Products.objects.get(pk=pk)
    form = ProductForm(request.POST, request.FILES, instance=data)
    if form.is_valid():
        print(1)
        form.save()
        return redirect('products:get_info')
    context = {
        'form': form
        }
    return render(request, 'update.html', context=context)

crud_pr2/templates/create.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
</form>

crud_pr2/templates/detail.html
<title>Detail</title>



<body>
<img src="{{ product.image.url }}"/><br>
Model: {{ product.model }}<br>
productrice: {{ product.productrice }}<br>
Make: {{ product.make }}<br>
CAtegory: {{ product.category }}<br>
Body: {{ product.body }}<hr/>

<a href="{% url 'products:get_info'%}" >home</a><br>
<a href="{% url 'products:update' product.pk %}" >Update</a><br>

</body>

crud_pr2/templates/index.html
<title>Home Page</title>

<h1>Home Page</h1><br>

<h3>Categories</h3><br>

<body>
{% for category in categories %}
<a href="{% url 'products:get_products' category.pk %}" >{{ category.name }}</a><br>
{% endfor %}
<a href="{% url 'products:add_products' %}" ><b>Add Products</b></a><br>


</body>

crud_pr2/templates/products.html
<title>Products</title>

<h1>Products</h1><br>


<body>
{% for product in products %}
    <a href="{% url 'products:detail' product.pk %}" >{{ product.model }}</a><hr>
{% endfor %}

</body>

crud_pr2/templates/update.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Save</button>
</form>